version: '3.1'

services:
  db:
    image: 'mongo:latest'
    container_name: gurusishyan_mongodb_container
    environment:
      - 'MONGODB_DATABASE="gurusishyan"'
    ports:
      - '27019:27017'
    expose:
      - 27019
