version: '3.1'

services:
  gurusishyan:
    build:
      dockerfile: DockerFile
      context: .
    image: 'gurushishyan:1.0.0'
  backend:
    image: 'gurushishyan:1.0.0'
    container_name: gurushishyan_backend_container
    working_dir: /app/gurushishyan/dist/apps/backend
    environment:
      - PORT=5000
      - NODE_NO_WARNINGS=1
      - DB_URL=mongodb://db:27017/gurusishyan?authSource=admin
      - DB_USERNAME=gurusishyan_db_user
      - DB_PASSWORD=guru@sishyan@2020
      - DB_HOST=0.0.0.0
      - DATABASE_NAME=gurusishyan
      - CONFIG_FILE_PATH=/Users/sathya/Documents/gs_acl.json
      - GOOGLE_CLIENT_ID=279728375283-3dva53gkisu070mi9octebk8fk3hgval.apps.googleusercontent.com
      - GOOGLE_SECRET=PdZ-xnr9L_jumnl2ECWb5V7u
      - BASE_DIR_PATH=/app/gurushishyan/storage
      - HOST=0.0.0.0
      - HOMEPAGELINK=http://localhost:4200
      - RESETLINK=http://localhost:4200/reset-password
      - SMTP_MAIL_API_KEY=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
      - RESET_PASSWORD_EMAIL=svvsathyanarayanan@gmail.com
      - RESET_PASSWORD_HTML_FOLDER=/app/gurushishyan/apps/backend/src/assets/html/reset-password.html
    restart: always
    ports:
      - '5000:5000'
    command: ['node','main.js']
    expose:
      - 5000
    volumes: 
      - '/Users/sathya/mapped_volumes/gurushishyan:/app/gurushishyan/dist/apps/backend/logs'  
      - '/Users/sathya/mapped_volumes/gurushishyan/storage:/app/gurushishyan/storage'
  db:
    image: 'mongo:latest'
    container_name: gurushishyan_mongodb_container
    environment:
      - 'MONGODB_DATABASE="gurusishyan"'
      - MONGO_INITDB_ROOT_USERNAME=gurusishyan_db_admin
      - MONGO_INITDB_ROOT_PASSWORD=gsdb@12345
    ports:
      - '27019:27017'
    expose:
      - 27019
