version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports: 
      - '5432:5432'