version: 2
jobs:
    build:
        branches:
        only:
            - develop
        docker:
            - image: 'circleci/node:8.0'
            - image: 'docker:17.09.1-ce-git'
        working_directory: ~/public
        steps:
            - checkout
            - setup_remote_docker
            - run: sudo npm install -g npm@latest
            - run: npm cache clear --force
            - restore_cache:
                key: 'dependency-cache-{{checksum "package.json"}}'
            - run: npm install
            - save_cache:
                key: 'dependency-cache-{{checksum "package.json"}}'
                paths:
                    - ./node_modules
            - restore_cache: 
                keys:
                    - 'v1-dependencies-{{ checksum "package.json" }}'
                    - v1-dependencies-
            
            - run: npm install
            - save_cache: 
                paths:
                  - node_modules
                key: 'v1-dependencies-{{ checksum "package.json" }}'
            - run: npm run test
            - run: 
                name: Build Success
                when: on_success
                command: >
                    docker --version

                    docker login -u=$DOCKER_LOGIN -p=$DOCKER_PASSWORD

                    docker build -t gurushishyan/gurushishyan:$CIRCLE_BRANCH
                    --build-arg
                    MACHINE_NAME=<application_name>-$CIRCLE_BRANCH .

                    docker push gurushishyan/gurushishyan:$CIRCLE_BRANCH

                    echo "Docker build made sucessfully!! for
                    <application_name> $CIRCLE_BRANCH"
            - run:
                name: Build Failure
                when: on_fail
                command: |
                    echo "ERROR building <application_name> $CIRCLE_BRANCH"
