version: 2
jobs:
    build:
        branches:
        only:
            - develop
        docker:
            - image: 'circleci/node'
            - image: 'docker'
        working_directory: ~/repo
        steps:
            - checkout
            - setup_remote_docker
            - run: sudo npm install -g npm@latest
            # - run: npm cache clear --force
            - restore_cache:
                key: 'dependency-cache-{{checksum "package.json"}}'
                when: on_success
                command: |
                     echo "Restoring cache successfull"
                     echo ${DOCKER_LOGIN}
                     echo ${DOCKER_PASSWORD}
            - run: npm install
            - save_cache:
                key: 'dependency-cache-{{checksum "package.json"}}'
                paths:
                    - ./node_modules
            - run: npm run test
            - run: 
                name: Build Success
                when: on_success
                context:
                    - gurushishyan_build
                command: |
                    echo "$DOCKER_PASSWORD" "$DOCKER_LOGIN"
                    echo "$DOCKER_PASSWORD" | docker login --username=$DOCKER_LOGIN --password-stdin
                    docker build -t gurushishyan/gurushishyan:$CIRCLE_BRANCH
                    --build-arg
                    MACHINE_NAME=gurushishyan-$CIRCLE_BRANCH .
                    docker push gurushishyan/gurushishyan:$CIRCLE_BRANCH
                    echo "Docker build made sucessfully!! for
                    gurushishyan $CIRCLE_BRANCH"
            - run:
                name: Build Failure
                when: on_fail
                command: |
                    echo "ERROR building gurushishyan $CIRCLE_BRANCH"
