version: 2
jobs:
    build:
        branches:
        only:
            - develop
        docker:
            - image: 'circleci/node@sha256:834b1a5a7fc8d41265f096e1a1d703cfcd779924e2e4ff50a1ddba7111352bb2'
            - image: 'docker@sha256:bc07b07e1ab1a365dcf5df859075b1bcaac0f50a0171b1305486b2f0e19963e4'
        working_directory: ~/repo
        steps:
            - checkout
            - setup_remote_docker
            - run: sudo npm install -g npm@latest
            # - run: npm cache clear --force
            - restore_cache:
                key: 'dependency-cache-{{checksum "package.json"}}'
            - run: npm install
            - save_cache:
                key: 'dependency-cache-{{checksum "package.json"}}'
                paths:
                    - ./node_modules
            - restore_cache: 
                keys:
                    - 'v1-dependencies-{{ checksum "package.json" }}'
                    - v1-dependencies-
            
            - run: npm install
            - save_cache: 
                paths:
                  - node_modules
                key: 'v1-dependencies-{{ checksum "package.json" }}'
            - run: npm run test
            - run: 
                name: Build Success
                when: on_success
                command: >
                    docker --version

                    docker login -u=$DOCKER_LOGIN -p=$DOCKER_PASSWORD

                    docker build -t gurushishyan/gurushishyan:$CIRCLE_BRANCH
                    --build-arg
                    MACHINE_NAME=<application_name>-$CIRCLE_BRANCH .

                    docker push gurushishyan/gurushishyan:$CIRCLE_BRANCH

                    echo "Docker build made sucessfully!! for
                    <application_name> $CIRCLE_BRANCH"
            - run:
                name: Build Failure
                when: on_fail
                command: |
                    echo "ERROR building <application_name> $CIRCLE_BRANCH"
