export const START_LOADER = 'START_LOADER'
export const STOP_LOADER = 'STOP_LOADER'

export const START_FULL_SCREEN_LOADER = 'START_FULL_SCREEN_LOADER'
export const STOP_FULL_SCREEN_LOADER = 'STOP_FULL_SCREEN_LOADER'