export const STUDENT_REGISTRATION_REQUEST = 'STUDENT_REGISTRATION_REQUEST'
export const STUDENT_REGISTRATION_SUCCESS = 'STUDENT_REGISTRATION_SUCCESS'
export const STUDENT_REGISTRATION_FAILURE = 'STUDENT_REGISTRATION_FAILURE'

export const TEACHER_REGISTRATION_REQUEST = 'TEACHER_REGISTRATION_REQUEST'
export const TEACHER_REGISTRATION_SUCCESS = 'TEACHER_REGISTRATION_SUCCESS'
export const TEACHER_REGISTRATION_FAILURE = 'TEACHER_REGISTRATION_FAILURE'


